name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: chetan/git-restore-mtime-action@v2
      - run: cargo publish --token ${CRATES_IO_API_TOKEN}
        env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
