name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run checks and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - uses: chetan/git-restore-mtime-action@v2
      - uses: actions-rust-lang/rustfmt@v1
      - uses: giraffate/clippy-action@v1
        with:
          reporter: github-check
      - run: cargo test
